name: loan_countdown
description: A new Flutter project for loan repayment countdown.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fl_chart: ^1.2.0
  intl: ^0.20.2 # Add this line
  screenshot: ^3.0.0
  path_provider: ^2.1.5
  share_plus: ^12.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1 # 패키지 추가
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

# 아이콘 설정 수정
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
